### ISSUE TITLE
Banner: pause no hover is not implemented

### ISSUE THREAD

**Issue by dremensayson** [titan-cebu/TLC-Surface-Treatment#109]

**Comment by kraisitb** [comment]
This seem to be an issue with 'slick' script which runs the slide including banner section. I've checked with other sites done by teammate and the issue exist across all projects.

If you have a site that has a pause-on-hover working could you supply me with a staging link as an example?

**Comment by dremensayson** [comment]
pause in  hover is important specially if the banner has text. 5 seconds is not enough for the user to read what is on the banner.
Please see sample site for the pause on hover implementation: http://austecelectrical-imp.stage.titanweb.com.au/

**Comment by kraisitb** [comment]
Thank you for the example.
