### ISSUE TITLE
Banner: image is pixelated, please cropped the image as per the design width and height

### ISSUE THREAD

**Issue by dremensayson** [titan-cebu/TLC-Surface-Treatment#111]
![image](https://cloud.githubusercontent.com/assets/17717843/16865265/f46748fc-4a95-11e6-9de6-0842a7ec0f31.png)

Banner images has different image attribute style
![image](https://cloud.githubusercontent.com/assets/17717843/16865502/cf08e690-4a97-11e6-9b86-b77c160ba055.png)
![image](https://cloud.githubusercontent.com/assets/17717843/16865505/d3bc7864-4a97-11e6-8ac3-93f904d01c6b.png)

**Comment by kraisitb** [comment]
The original image is not height enough to fit the banner section height so it is stretch and scaled by the script in order to fit the section.

**Comment by dremensayson** [comment]
newly uploaded big image occupied the entire page, it should be cropped based on the design 
![image](https://cloud.githubusercontent.com/assets/17717843/17128825/04ad04e0-5342-11e6-9660-587c610aa632.png)

**Comment by kraisitb** [comment]
Should be fixed now as part of issue #117

**Comment by dremensayson** [comment]
image still pixelated. I've checked the original images from the media in the back-end image dimension is  2100 x 640 which it can fit to the height specified in the design without stretching the images.

**Comment by kraisitb** [comment]
The image is actually not stretch but it is a bit pixelated originally from the mock.

Please see the link below for the actual image uploaded.
http://tlc-imp.stage.titanweb.com.au/wp-content/uploads/2014/08/banner2-1.jpg
