### ISSUE TITLE
Homepage - Resolution Checking: banner is not same height in lower resolution

### ISSUE THREAD

**Issue by dremensayson** [titan-cebu/TLC-Surface-Treatment#117]
![image](https://cloud.githubusercontent.com/assets/17717843/16867151/dcea1148-4aa2-11e6-9104-a72ea37e56b1.png)

**Comment by kraisitb** [comment]
The banner images are currently set as 100% width with dynamic height in order to support various image dimension (in this case, mostly rectangular images and 1 square image).

However, a dynamic re-positioning of the banner content below the image is already in place.

**Comment by dremensayson** [comment]
Please see sample site: http://joondalup-turf-farm-imp.stage.titanweb.com.au, image used is same
