### ISSUE TITLE
Pre-footer: please implement PM Notes

### ISSUE THREAD

**Issue by dremensayson** [titan-cebu/TLC-Surface-Treatment#12]
![image](https://cloud.githubusercontent.com/assets/17717843/16552539/6fd9defa-41f4-11e6-98a2-b8576d94b4c4.png)

**Comment by kraisitb** [comment]
Based on the mock, the static text below the logo is already changed into sitemap links.

I think we should keep the logo.

**Comment by dremensayson** [comment]
please change the logo to sitemap text header

**Comment by dremensayson** [comment]
no fixes made

**Comment by kraisitb** [comment]
I've already changed the logo in the footer into 'sitemap' text. Could you try refresh/clearing cache and verify this again?
