### ISSUE TITLE
Services and Blog Single: order list is  not indented and unstyled unordered list

### ISSUE THREAD

**Issue by dremensayson** [titan-cebu/TLC-Surface-Treatment#125]
Please apply fixes to all custom post single plage.

![image](https://cloud.githubusercontent.com/assets/17717843/17128149/490c9f2e-533d-11e6-93f3-f6bd4f5a021e.png)

![image](https://cloud.githubusercontent.com/assets/17717843/17128162/58e7692e-533d-11e6-97d6-872bdd78b489.png)

**Comment by kraisitb** [comment]
The remaining ones are paragraph text of list not an actual ordered/unorderd list.

Please try inspecting the content such as this one http://tlc-imp.stage.titanweb.com.au/service/service-1/ to see that they are <p> tag not <ol> or <ul>.

**Comment by dremensayson** [comment]
It's pasted from the sample document with listed content and it should displayed as it is from the source

**Comment by kraisitb** [comment]
Please check in the backend. You can update these to be a proper list and the css would then be applied.

![2016-07-27_14-05-14](https://cloud.githubusercontent.com/assets/18692126/17166792/4f610c54-5403-11e6-9075-b41ab2d58044.png)
