### ISSUE TITLE
Banner: incorrect image height compared to the design

### ISSUE THREAD

**Issue by dremensayson** [titan-cebu/TLC-Surface-Treatment#127]
![image](https://cloud.githubusercontent.com/assets/17717843/17170981/224c3ef0-5421-11e6-9e7a-75319cf3156e.png)

![image](https://cloud.githubusercontent.com/assets/17717843/17170994/33771e70-5421-11e6-9a00-55471e555353.png)

**Comment by kraisitb** [comment]
default banner image height (cropping) is now set to 640px as per original image in the mock.

Note - as it is responsive it would not be exact 640px height on screen less than 1600px or so.

**Comment by dremensayson** [comment]
Banner has different height in front-end but same height in the back-end.

![image](https://cloud.githubusercontent.com/assets/17717843/17199452/905f1636-54af-11e6-8198-02c6748e1f66.png)

**Comment by kraisitb** [comment]
I've tried re-uploading the first banner image. The new image in use is now having a 1920 x 640 dimension.

This would also fix the issue #128

**Comment by dremensayson** [comment]
As you can see all uploaded banner has the same dimension 1920 x 640, but in the front-end it has uneven height. The page move up and down due to uneven height of the banner images. Please see uploaded video. http://screencast.com/t/IjQ5obY4UU

**Comment by kraisitb** [comment]
I've re-uploaded the 2 images and all have the same height now.

**Comment by dremensayson** [comment]
issue still exist. please check. uploaded new banner with title "TEST" image dimension is 2100 x 640.

**Comment by kraisitb** [comment]
![image](https://cloud.githubusercontent.com/assets/18692126/17324204/97f1f962-58cf-11e6-8d6e-ebad9921a6e9.png)

The image is an old image. Please try uploading a new one.

For more details please refer to my comment on issue #128 .
