### ISSUE TITLE
All Inner and Single Pages: incorrect feautered image dimension as per design. Please follow the single page design

### ISSUE THREAD

**Issue by dremensayson** [titan-cebu/TLC-Surface-Treatment#130]
![image](https://cloud.githubusercontent.com/assets/17717843/17200250/3a0bf32e-54b6-11e6-9cf4-eb1702e56b1e.png)

**Comment by dremensayson** [comment]
Please cropped image to achieved desired image dimension as per design.
![image](https://cloud.githubusercontent.com/assets/17717843/17289939/6e566f6e-580e-11e6-8692-a7064ed77851.png)
![image](https://cloud.githubusercontent.com/assets/17717843/17289947/77a77482-580e-11e6-8d03-898d08fe861b.png)

**Comment by kraisitb** [comment]
Featured images need to be re-uploaded in order for the new image cropping resolution to be applied.

For example, http://tlc-imp.stage.titanweb.com.au/services/.

**Comment by kraisitb** [comment]
Same reason as issue #128 .

If newly image uploaded is in used it would look like this http://tlc-imp.stage.titanweb.com.au/blog/blog1/.
