### ISSUE TITLE
Blog: page content is not displayed in the front-end but set in the back-end

### ISSUE THREAD

**Issue by dremensayson** [titan-cebu/TLC-Surface-Treatment#134]
![image](https://cloud.githubusercontent.com/assets/17717843/17201871/8f068190-54c6-11e6-9c94-9e11524b0a7b.png)

**Comment by kraisitb** [comment]
Please note that the breadcrumb of blog single page would be 'Home / Blog 1' instead of 'Home / Blog / Blog 1'.

This is due to blog page setting of WP backend is set to empty in order to be able to display blog page editor content (basically making 'blog' a page rather than a blog).
