### ISSUE TITLE
Gallery: incorrect image dimension used compared to the design

### ISSUE THREAD

**Issue by dremensayson** [titan-cebu/TLC-Surface-Treatment#138]
Design Image Dimension: 189x189
Implementation in WebPage Image Dimension: 150x150

 ![image](https://cloud.githubusercontent.com/assets/17717843/17203234/c00071a2-54d0-11e6-81bb-463cb8e7a145.png)

![image](https://cloud.githubusercontent.com/assets/17717843/17203421/fe065902-54d1-11e6-8a65-51b89853d23d.png)

**Comment by kraisitb** [comment]
Fixed as part of issue #139
