### ISSUE TITLE
Homepage - Services: incorrect font size, font family and text transform used compared to the design

### ISSUE THREAD

**Issue by dremensayson** [titan-cebu/TLC-Surface-Treatment#23]
![image](https://cloud.githubusercontent.com/assets/17717843/16554065/1d222e50-41ff-11e6-9260-230f78ce56fa.png)

**Comment by dremensayson** [comment]
font size and font family - fixed
text transform still an issue.

**Comment by dremensayson** [comment]
text transform issue still exist. please apply text transform: uppercase; to achieved the design
![image](https://cloud.githubusercontent.com/assets/17717843/16862226/9717f57c-4a7a-11e6-9ff5-18c6ec7722a8.png)

**Comment by kraisitb** [comment]
Text transform already applied.
