### ISSUE TITLE
Homepage - Resolution Checking: please apply burger menu in 768 and below resolution.

### ISSUE THREAD

**Issue by dremensayson** [titan-cebu/TLC-Surface-Treatment#31]
![image](https://cloud.githubusercontent.com/assets/17717843/16571858/f22a1cc6-4294-11e6-88f9-41e43a8ffca6.png)

**Comment by kraisitb** [comment]
Burger menu will appear when the resolution is 1200px and below.

This is due to limited space for the navigation menu as the menu item would fall down into a new line at around 1100px.

**Comment by dremensayson** [comment]
Please refer to this website:
http://stewartspestcontrol-imp.stage.titanweb.com.au/

**Comment by kraisitb** [comment]
Thanks for the example.

I've moved the break point for burger menu to 900px or lower.

**Comment by dremensayson** [comment]
I've moved the break point for burger menu to 900px or lower. - not implemented, burger menu still in 1200px.
