### ISSUE TITLE
Homepage - Resolution Checking: banner content not retain its alignment in the 768 and below resolution

### ISSUE THREAD

**Issue by dremensayson** [titan-cebu/TLC-Surface-Treatment#33]
![image](https://cloud.githubusercontent.com/assets/17717843/16571919/76ab5f3c-4295-11e6-8c69-8ac8eae33ae3.png)

**Comment by kraisitb** [comment]
In 768px and lower resolution we do not have enough space to place the play button along side with the banner content.

In my opinion, aligning all the banner elements in the center would look better than keeping them left aligned as in a resolution higher than 768px.

**Comment by kraisitb** [comment]
Banner content will now reposition automatically depends on banner image's height.
