### ISSUE TITLE
Pre footer - Sitemap: please apply hover state

### ISSUE THREAD

**Issue by dremensayson** [titan-cebu/TLC-Surface-Treatment#34]
![image](https://cloud.githubusercontent.com/assets/17717843/16572004/5888f392-4296-11e6-95c8-8bcd56480785.png)

**Comment by kraisitb** [comment]
The links already have hover state applied (you can see in the screenshot that the text turn dark gray when hover).

Could you please provide more details of what change to be done?

**Comment by dremensayson** [comment]
change the gray color to the red color used as per site scheme
