### ISSUE TITLE
Homepage - Resolution Checking: lead ins title is not aligned with the image in 434 to 480 resolution

### ISSUE THREAD

**Issue by dremensayson** [titan-cebu/TLC-Surface-Treatment#35]
![image](https://cloud.githubusercontent.com/assets/17717843/16572280/96817644-4299-11e6-9489-ea3ccfe9e6fa.png)

**Comment by kraisitb** [comment]
I've checked the issue following the resolution guide mentioned but unable to replicate the issue.

The image and leadin title box is resizing properly with respect to browser size.

**Comment by dremensayson** [comment]
please set your screen viewport to 480px and slowly resize to lower resolution. uploaded shows all browsers has the same issue.
![image](https://cloud.githubusercontent.com/assets/17717843/16861943/0841e27e-4a78-11e6-8538-bae82497eab6.png)
