### ISSUE TITLE
About Us - Sidebar: missing title and not aligned with the page content compared to the design

### ISSUE THREAD

**Issue by dremensayson** [titan-cebu/TLC-Surface-Treatment#38]
![image](https://cloud.githubusercontent.com/assets/17717843/16572563/7e41f2f4-429c-11e6-8138-3fccb88187eb.png)

**Comment by kraisitb** [comment]
Form title is retrieved from widget's title field. Gravity form heading is hidden to prevent duplicate title.

**Comment by dremensayson** [comment]
fix the missing title
