### ISSUE TITLE
About Us - Sidebar: form is wider compared to the design

### ISSUE THREAD

**Issue by dremensayson** [titan-cebu/TLC-Surface-Treatment#39]
![image](https://cloud.githubusercontent.com/assets/17717843/16572598/d2fd0bee-429c-11e6-9027-ea6b319eec9d.png)

**Comment by kraisitb** [comment]
Bootstrap grid is used to handle the layout so the width / dimension would not be exactly the same to the mock and would also be vary when resizing browser as well for responsive support.

**Comment by dremensayson** [comment]
design is bootstrap grid ready. design is 3 columns while the implementation is 4 columns.
![image](https://cloud.githubusercontent.com/assets/17717843/16796200/f5f8cd36-4913-11e6-966a-aca980fbe8d8.png)
