### ISSUE TITLE
All Inner Pages: heading has incorrect font size compared to the design

### ISSUE THREAD

**Issue by dremensayson** [titan-cebu/TLC-Surface-Treatment#40]
![image](https://cloud.githubusercontent.com/assets/17717843/16572687/df7506d2-429d-11e6-807a-af1c1bafbbd0.png)

**Comment by dremensayson** [comment]
we will verify this if the issue https://github.com/titan-cebu/TLC-Surface-Treatment/issues/99 is already fix

**Comment by kraisitb** [comment]
I've added my comment on issue #99 . Please check.

**Comment by dremensayson** [comment]
still incorrect font size used in heading 3 and 4 as per design
1. heading 3 is 32px in design but 31px in website
![image](https://cloud.githubusercontent.com/assets/17717843/16861803/cb7a5cd2-4a76-11e6-972e-0f7e264e94f7.png)
2. heading 4 is 28px in design but 27 in website
![image](https://cloud.githubusercontent.com/assets/17717843/16861808/d26c7e12-4a76-11e6-92b6-be8bd99a628c.png)
