### ISSUE TITLE
About Us - Resolution Checking: page is broken when resizing the page

### ISSUE THREAD

**Issue by dremensayson** [titan-cebu/TLC-Surface-Treatment#44]
![image](https://cloud.githubusercontent.com/assets/17717843/16572826/88c063f2-429f-11e6-8a63-89d8cf5a8911.png)

**Comment by kraisitb** [comment]
I cannot see the error as in the screenshot. Could you please try rechecking this again or provide me exact resolution that cause this issue if possible?
