### ISSUE TITLE
Services:post image is smaller compared to the design

### ISSUE THREAD

**Issue by dremensayson** [titan-cebu/TLC-Surface-Treatment#47]
![image](https://cloud.githubusercontent.com/assets/17717843/16573197/ba4e0aa6-42a3-11e6-8cd1-4e8462974a2c.png)

**Comment by kraisitb** [comment]
Bootstrap grid is used to handle the layout for listing page so the dimension is not exactly the same as in the mock (quite close to the mock).

The image width will also be varied across browser sizes for responsive purpose.

**Comment by dremensayson** [comment]
image size can be considered if it has 5px difference but in this case difference is 31px which is to big. We can still achieve the 261x261 image size. Please see the uploaded image
![image](https://cloud.githubusercontent.com/assets/17717843/16794748/3ed3b80c-490c-11e6-94c1-be2d7572a5c4.png)

**Comment by kraisitb** [comment]
Ok, I've tried customising the layout without using bootstrap. Please verify the issue again.

**Comment by dremensayson** [comment]
image is already achieved but please retain the position of the post content as per design. post content should be horizontally align to the image.

**Comment by dremensayson** [comment]
image should have the same size specified in the given the design

**Comment by kraisitb** [comment]
Max-width:261px; added. The height is left vary depends on the image dimension.

**Comment by dremensayson** [comment]
Images from the list view are all regular images as per standard Images must be cropped according to the dimensions set from the design. Please see link https://knowledgebase.titanweb.com.au/outdated-category/image-sizes

**Comment by kraisitb** [comment]
I've added a new image size as per the guide for services now.

However, the image need to be re-uploaded for the new size to be applied. You can see the updated one on the 'Service 3' entry.
