### ISSUE TITLE
Admin - Blog Page: unable to add page content

### ISSUE THREAD

**Issue by dremensayson** [titan-cebu/TLC-Surface-Treatment#52]
![image](https://cloud.githubusercontent.com/assets/17717843/16573450/9612f446-42a6-11e6-9b99-a1ab6395bbbb.png)

**Comment by kraisitb** [comment]
I don't think you can add page content when setting the page as wordpress 'blog' page.

If we can do that could you please give me an example of a project I can use as a guide?

**Comment by dremensayson** [comment]
Please refer to this website
http://alfredskitchen-imp.stage.titanweb.com.au/blog/

**Comment by kraisitb** [comment]
Thanks for the example.
