### ISSUE TITLE
FAQ: change the slug and link from "faqs" to "faq" to be consistent in the menu title

### ISSUE THREAD

**Issue by dremensayson** [titan-cebu/TLC-Surface-Treatment#64]
![image](https://cloud.githubusercontent.com/assets/17717843/16640344/cd8360f8-4429-11e6-9618-55e1d5592b4f.png)

**Comment by kraisitb** [comment]
We need to keep the slug as 'faqs' as it would collide with custom post type 'faq' registered, of which would result in 404 error.
