### ISSUE TITLE
Contact Us: broken form when email address is invalid

### ISSUE THREAD

**Issue by dremensayson** [titan-cebu/TLC-Surface-Treatment#75]
![image](https://cloud.githubusercontent.com/assets/17717843/16642097/f4d45878-4439-11e6-810b-be6e606d7945.png)

**Comment by dremensayson** [comment]
we will verify this issue when this https://github.com/titan-cebu/TLC-Surface-Treatment/issues/94 is already fix

**Comment by kraisitb** [comment]
#94 is working AOK from my end. Please try to verify this issue again.
