### ISSUE TITLE
FOUC

### ISSUE THREAD

**Issue by dremensayson** [titan-cebu/TLC-Surface-Treatment#98]
![image](https://cloud.githubusercontent.com/assets/17717843/16794875/e003b1fa-490c-11e6-813a-3d72831af3f3.png)

**Comment by kraisitb** [comment]
Should be fixed now. Please re-verify.

**Comment by dremensayson** [comment]
Issue still exist, please check the firefox then disable the java script to check if the FOUC already fix.
