### ISSUE TITLE
Admin - Pages: unable to set heading in the background

### ISSUE THREAD

**Issue by dremensayson** [titan-cebu/TLC-Surface-Treatment#99]
![image](https://cloud.githubusercontent.com/assets/17717843/16795740/9c4fca7a-4911-11e6-8591-d1283992185c.png)

**Comment by kraisitb** [comment]
Did you mean the dropdown list to select either H2, H3, and others?

If so it is there but you'd need to toggle its visibility by clicking the last item in the toolbar.
